apiVersion: v1
kind: Pod
metadata:
  name: myweb
  labels:
    purpose: myweb
spec:
  containers:
  - name: myweb-container
    image: myweb
    env:
    - name: PROFILE_NAME
      value: "prod"
    - name: APP_VERSION
      value: "v2"