apiVersion: v1
kind: Pod
metadata:
  name: myweb-dev
  labels:
    purpose: myweb-dev
spec:
  containers:
  - name: myweb-dev-container
    image: myweb
    env:
    - name: PROFILE_NAME
      value: "dev"
    - name: APP_VERSION
      value: "v1"